const urgentHomeAppointments = [
  {
    "id": 1,
    "code": "HAP-URG001A",
    "donor_id": 45,
    "hospital_id": 3,
    "hospital_name": "Rafik Hariri University Hospital",
    "appointment_id": 102,
    "appointment_type": "urgent",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-21",
    "appointment_time": "14:30:00",
    "due_date": "2026-01-21",
    "due_time": "18:00:00",
    "blood_type": "O-",
    "weight": 68,
    "address": "Jnah, Beirut, Lebanon",
    "latitude": 33.8547,
    "longitude": 35.4856,
    "medical_conditions": ["None"],
    "emerg_contact": "Sarah Johnson",
    "emerg_phone": "+961-1-555-0123",
    "note": "Patient with critical O- blood needed for emergency surgery",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 2,
    "code": "HAP-URG002B",
    "donor_id": 78,
    "hospital_id": 5,
    "hospital_name": "American University of Beirut Medical Center",
    "appointment_id": 105,
    "appointment_type": "urgent",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-21",
    "appointment_time": "16:00:00",
    "due_date": "2026-01-21",
    "due_time": "23:00:00",
    "blood_type": "AB+",
    "weight": 72,
    "address": "Hamra, Beirut, Lebanon",
    "latitude": 33.9006,
    "longitude": 35.4815,
    "medical_conditions": ["Allergies to latex"],
    "emerg_contact": "Michael Chen",
    "emerg_phone": "+961-1-555-0456",
    "note": "Rare AB+ blood urgently needed for accident victim",
    "state": "pending",
    "phlebotomist_id": 12,
  },
  {
    "id": 3,
    "code": "HAP-URG003C",
    "donor_id": 92,
    "hospital_id": 2,
    "hospital_name": "Hotel Dieu de France Hospital",
    "appointment_id": 108,
    "appointment_type": "urgent",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-21",
    "appointment_time": "10:30:00",
    "due_date": "2026-01-21",
    "due_time": "15:30:00",
    "blood_type": "A-",
    "weight": 65,
    "address": "Achrafieh, Beirut, Lebanon",
    "latitude": 33.8938,
    "longitude": 35.5089,
    "medical_conditions": ["None"],
    "emerg_contact": "Emily Rodriguez",
    "emerg_phone": "+961-1-555-0789",
    "note": "Cancer patient requires immediate A- blood transfusion",
    "state": "confirmed",
    "phlebotomist_id": 8,
  },
  {
    "id": 4,
    "code": "HAP-URG004D",
    "donor_id": 134,
    "hospital_id": 7,
    "hospital_name": "Saint George Hospital",
    "appointment_id": 112,
    "appointment_type": "urgent",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-21",
    "appointment_time": "12:00:00",
    "due_date": "2026-01-21",
    "due_time": "20:00:00",
    "blood_type": "B+",
    "weight": 78,
    "address": "Achrafieh, Beirut, Lebanon",
    "latitude": 33.8897,
    "longitude": 35.5126,
    "medical_conditions": ["Mild hypertension (controlled)"],
    "emerg_contact": "David Kim",
    "emerg_phone": "+961-1-555-0321",
    "note": "Urgent need for surgery scheduled this evening",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 5,
    "code": "HAP-URG005E",
    "donor_id": 167,
    "hospital_id": 4,
    "hospital_name": "Lebanese Red Cross",
    "appointment_id": 115,
    "appointment_type": "urgent",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-21",
    "appointment_time": "09:00:00",
    "due_date": "2026-01-21",
    "due_time": "14:00:00",
    "blood_type": "O+",
    "weight": 70,
    "address": "Spears Street, Beirut, Lebanon",
    "latitude": 33.8937,
    "longitude": 35.5017,
    "medical_conditions": ["None"],
    "emerg_contact": "Lisa Martinez",
    "emerg_phone": "+961-1-555-0654",
    "note": "Emergency room patient with severe blood loss",
    "state": "confirmed",
    "phlebotomist_id": 15,
  },
];
const regularHomeAppointments = [
  {
    "id": 6,
    "code": "HAP-REG001F",
    "donor_id": 23,
    "hospital_id": 1,
    "hospital_name": "Makassed General Hospital",
    "appointment_id": 120,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-25",
    "appointment_time": "10:00:00",
    "start_time": "09:00:00",
    "end_time": "17:00:00",
    "gap_hours": 1.5,
    "blood_type": null,
    "weight": 75,
    "address": "Tarik Jdide, Beirut, Lebanon",
    "latitude": 33.8855,
    "longitude": 35.5134,
    "medical_conditions": ["None"],
    "emerg_contact": "John Smith",
    "emerg_phone": "+961-1-555-1111",
    "note": "Regular donation, first-time home donor",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 7,
    "code": "HAP-REG002G",
    "donor_id": 56,
    "hospital_id": 3,
    "hospital_name": "Rafik Hariri University Hospital",
    "appointment_id": 123,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-01-28",
    "appointment_time": "14:00:00",
    "start_time": "08:00:00",
    "end_time": "18:00:00",
    "gap_hours": 2.0,
    "blood_type": null,
    "weight": 82,
    "address": "Jnah, Beirut, Lebanon",
    "latitude": 33.8547,
    "longitude": -73.9845,
    "medical_conditions": ["Mild asthma"],
    "emerg_contact": "Anna Wilson",
    "emerg_phone": "+1-555-2222",
    "note": "Prefers morning appointments but flexible",
    "state": "confirmed",
    "phlebotomist_id": 6,
  },
  {
    "id": 8,
    "code": "HAP-REG003H",
    "donor_id": 89,
    "hospital_id": 6,
    "appointment_id": 127,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-02-03",
    "appointment_time": "11:30:00",
    "start_time": "09:00:00",
    "end_time": "16:00:00",
    "gap_hours": 1.0,
    "blood_type": null,
    "weight": 68,
    "address": "789 River Road, Riverside, Metro City",
    "latitude": 40.7567,
    "longitude": -73.9612,
    "medical_conditions": ["None"],
    "emerg_contact": "Robert Taylor",
    "emerg_phone": "+1-555-3333",
    "note": "Regular donor, donates every 3 months",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 9,
    "code": "HAP-REG004I",
    "donor_id": 112,
    "hospital_id": 2,
    "appointment_id": 131,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-02-08",
    "appointment_time": "15:30:00",
    "start_time": "10:00:00",
    "end_time": "19:00:00",
    "gap_hours": 1.5,
    "blood_type": null,
    "weight": 71,
    "address": "234 Garden Street, Green Valley, Metro City",
    "latitude": 40.7445,
    "longitude": -73.9778,
    "medical_conditions": ["Type 2 diabetes (well-controlled)"],
    "emerg_contact": "Patricia Anderson",
    "emerg_phone": "+1-555-4444",
    "note": "Needs to eat before donation due to diabetes",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 10,
    "code": "HAP-REG005J",
    "donor_id": 145,
    "hospital_id": 5,
    "appointment_id": 135,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-02-12",
    "appointment_time": "09:30:00",
    "start_time": "08:00:00",
    "end_time": "17:00:00",
    "gap_hours": 2.0,
    "blood_type": null,
    "weight": 77,
    "address": "567 Hill Avenue, Mountain View, Metro City",
    "latitude": 40.7623,
    "longitude": -73.9556,
    "medical_conditions": ["None"],
    "emerg_contact": "James Brown",
    "emerg_phone": "+1-555-5555",
    "note": "Works from home, flexible with time",
    "state": "confirmed",
    "phlebotomist_id": 11,
  },
  {
    "id": 11,
    "code": "HAP-REG006K",
    "donor_id": 178,
    "hospital_id": 8,
    "appointment_id": 139,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-02-15",
    "appointment_time": "13:00:00",
    "start_time": "09:00:00",
    "end_time": "18:00:00",
    "gap_hours": 1.5,
    "blood_type": null,
    "weight": 80,
    "address": "890 Lake Shore Drive, Lakeside, Metro City",
    "latitude": 40.7501,
    "longitude": -73.9689,
    "medical_conditions": ["Seasonal allergies"],
    "emerg_contact": "Maria Garcia",
    "emerg_phone": "+1-555-6666",
    "note": "Has donated 15+ times, experienced donor",
    "state": "pending",
    "phlebotomist_id": null,
  },
  {
    "id": 12,
    "code": "HAP-REG007L",
    "donor_id": 201,
    "hospital_id": 4,
    "appointment_id": 143,
    "appointment_type": "regular",
    "donation_type": "Home Blood Donation",
    "appointment_date": "2026-02-20",
    "appointment_time": "16:00:00",
    "start_time": "10:00:00",
    "end_time": "19:00:00",
    "gap_hours": 1.0,
    "blood_type": null,
    "weight": 73,
    "address": "123 Forest Lane, Woodland Park, Metro City",
    "latitude": 40.7389,
    "longitude": -73.9823,
    "medical_conditions": ["None"],
    "emerg_contact": "Christopher Lee",
    "emerg_phone": "+1-555-7777",
    "note": "Afternoon appointments preferred due to work schedule",
    "state": "pending",
    "phlebotomist_id": null,
  },
];
